from __future__ import annotations

from .model import DieFace, PlanetCard, Resource


# Sourced from local base-game planet guide: bgg161447.pdf.
BASE_PLANETS = [
    PlanetCard("jakks", "Jakks", DieFace.DIPLOMACY, 2, 1, Resource.CULTURE, "gain_1_culture", "Acquire 1 culture.", ("culture",)),
    PlanetCard("vici_ks156", "Vici-KS156", DieFace.ECONOMY, 2, 1, Resource.ENERGY, "gain_1_energy", "Acquire 1 energy.", ("energy",)),
    PlanetCard("drewkaiden", "Drewkaiden", DieFace.ECONOMY, 2, 1, Resource.CULTURE, "advance_diplomacy_1", "Advance one of your ships on a diplomacy colony track 1 space.", ("diplomacy", "colonize")),
    PlanetCard("leandra", "Leandra", DieFace.DIPLOMACY, 2, 1, Resource.ENERGY, "advance_economy_1", "Advance one of your ships on an economy colony track 1 space.", ("economy", "colonize")),
    PlanetCard("birkomius", "Birkomius", DieFace.DIPLOMACY, 2, 1, Resource.CULTURE, "follow_gain_culture", "If you are followed this turn, acquire 1 culture per follow.", ("culture", "follow")),
    PlanetCard("bisschop", "Bisschop", DieFace.ECONOMY, 2, 1, Resource.ENERGY, "follow_gain_energy", "If you are followed this turn, acquire 1 energy per follow.", ("energy", "follow")),
    PlanetCard("tifnod", "Tifnod", DieFace.ECONOMY, 2, 1, Resource.CULTURE, "regress_enemy_diplomacy_1", "Regress one enemy ship on a diplomacy colony track 1 space.", ("attack", "diplomacy")),
    PlanetCard("vizcarra", "Vizcarra", DieFace.DIPLOMACY, 2, 1, Resource.ENERGY, "regress_enemy_economy_1", "Regress one enemy ship on an economy colony track 1 space.", ("attack", "economy")),
    PlanetCard("mj_120210", "MJ-120210", DieFace.DIPLOMACY, 3, 2, Resource.ENERGY, "gain_2_energy", "Acquire 2 energy.", ("energy",)),
    PlanetCard("helios", "Helios", DieFace.DIPLOMACY, 3, 2, Resource.CULTURE, "cycle_unoccupied_planet", "Discard an unoccupied planet in the middle and replace it with a new planet.", ("market",)),
    PlanetCard("mared", "Mared", DieFace.ECONOMY, 3, 2, Resource.ENERGY, "lowest_empire_upgrade_discount", "If your empire level is the lowest, upgrade your empire for 1 less energy or culture.", ("upgrade",)),
    PlanetCard("lureena", "Lureena", DieFace.ECONOMY, 3, 2, Resource.CULTURE, "upgrade_empire_mixed", "Immediately upgrade your empire; you may spend energy and/or culture.", ("upgrade",)),
    PlanetCard("zalax", "Zalax", DieFace.DIPLOMACY, 3, 2, Resource.CULTURE, "reroll_inactive_dice", "Reroll any number of your inactive dice.", ("dice_control",)),
    PlanetCard("hoefker", "Hoefker", DieFace.ECONOMY, 3, 2, Resource.CULTURE, "spend_energy_gain_2_culture", "Spend 1 energy to acquire 2 culture.", ("energy", "culture")),
    PlanetCard("clj_0517", "CLJ-0517", DieFace.ECONOMY, 3, 2, Resource.ENERGY, "steal_1_culture", "Steal 1 culture from another player.", ("attack", "culture")),
    PlanetCard("la_torres", "La-Torres", DieFace.DIPLOMACY, 3, 2, Resource.ENERGY, "steal_1_energy", "Steal 1 energy from another player.", ("attack", "energy")),
    PlanetCard("pembertonia_major", "Pembertonia-Major", DieFace.ECONOMY, 4, 3, Resource.ENERGY, "convert_culture_to_energy", "Convert any number of culture into energy.", ("energy", "culture")),
    PlanetCard("omicron_fenzi", "Omicron Fenzi", DieFace.DIPLOMACY, 4, 3, Resource.CULTURE, "convert_energy_to_culture", "Convert any number of energy into culture.", ("energy", "culture")),
    PlanetCard("nagato", "Nagato", DieFace.ECONOMY, 4, 3, Resource.ENERGY, "spend_culture_move_2", "Spend 1 culture to move two of your ships.", ("mobility",)),
    PlanetCard("padraigin_3110", "Padraigin-3110", DieFace.ECONOMY, 4, 3, Resource.CULTURE, "spend_2_culture_advance_diplomacy_2", "Spend 2 culture to advance one of your ships on a diplomacy colony track 2 spaces.", ("diplomacy", "colonize")),
    PlanetCard("jorg", "Jorg", DieFace.DIPLOMACY, 4, 3, Resource.CULTURE, "spend_2_culture_regress_enemy_2", "Spend 2 culture to regress one enemy ship 2 spaces.", ("attack", "culture")),
    PlanetCard("nakagawakozi", "Nakagawakozi", DieFace.DIPLOMACY, 4, 3, Resource.ENERGY, "spend_2_energy_advance_economy_2", "Spend 2 energy to advance one of your ships on an economy colony track 2 spaces.", ("economy", "colonize")),
    PlanetCard("brumbaugh", "Brumbaugh", DieFace.DIPLOMACY, 4, 3, Resource.ENERGY, "spend_2_energy_regress_two_enemies_1", "Spend 2 energy to regress two enemy ships 1 space.", ("attack", "energy")),
    PlanetCard("umbra_forum", "Umbra-Forum", DieFace.ECONOMY, 4, 3, Resource.CULTURE, "use_uncolonized_planet", "Utilize the action of an un-colonized planet.", ("market",)),
    PlanetCard("jac_110912", "JAC-110912", DieFace.ECONOMY, 5, 5, Resource.CULTURE, "gain_2_culture_others_1", "Acquire 2 culture; all other players acquire 1 culture.", ("culture", "table")),
    PlanetCard("gleam_zanier", "Gleam-Zanier", DieFace.DIPLOMACY, 5, 5, Resource.ENERGY, "gain_2_energy_others_1", "Acquire 2 energy; all other players acquire 1 energy.", ("energy", "table")),
    PlanetCard("maia", "Maia", DieFace.DIPLOMACY, 5, 5, Resource.CULTURE, "discard_2_dice_gain_2_each", "Discard 2 inactive dice, acquire 2 energy and 2 culture.", ("energy", "culture", "dice_control")),
    PlanetCard("andellouxian_6", "Andellouxian-6", DieFace.ECONOMY, 5, 5, Resource.CULTURE, "displace_ship_gain_level_resource", "Displace one of your orbiting ships, acquire energy or culture equal to that ship's level.", ("mobility", "energy", "culture")),
    PlanetCard("walsfeo", "Walsfeo", DieFace.ECONOMY, 5, 5, Resource.ENERGY, "pay_culture_use_player_colony", "Pay 1 culture to a player to utilize one of their colonized planets.", ("culture", "table")),
    PlanetCard("sargus_36", "Sargus-36", DieFace.DIPLOMACY, 5, 5, Resource.CULTURE, "pay_energy_use_player_colony", "Pay 1 energy to a player to utilize one of their colonized planets.", ("energy", "table")),
    PlanetCard("zavodnick", "Zavodnick", DieFace.ECONOMY, 5, 5, Resource.ENERGY, "perform_any_action_free_follow", "Perform any one action; all other players may follow that action for free.", ("wild", "follow")),
    PlanetCard("bsw_10_1", "BSW-10-1", DieFace.DIPLOMACY, 5, 5, Resource.ENERGY, "regress_own_then_advance_other", "Regress one of your ships 1 space, then advance another one of your ships 1 space.", ("colonize",)),
    PlanetCard("aughmoore", "Aughmoore", DieFace.DIPLOMACY, 6, 7, Resource.ENERGY, "gain_culture_for_landed", "Acquire culture for every ship landed in your galaxy.", ("culture",)),
    PlanetCard("shouhua", "Shouhua", DieFace.DIPLOMACY, 6, 7, Resource.ENERGY, "advance_any_1", "Advance a ship 1 space.", ("colonize",)),
    PlanetCard("nibiru", "Nibiru", DieFace.DIPLOMACY, 6, 7, Resource.CULTURE, "follow_tax_2_culture", "Enemies must pay 2 culture per follow this turn.", ("culture", "follow")),
    PlanetCard("gort", "Gort", DieFace.ECONOMY, 6, 7, Resource.ENERGY, "move_track_equal_level", "Move one of your ships to another colony track at an equal level.", ("mobility",)),
    PlanetCard("terra_bettia", "Terra-Bettia", DieFace.DIPLOMACY, 6, 7, Resource.ENERGY, "others_advance_then_you_advance_2", "Other players advance a ship 1 space, then you advance a ship 2 spaces.", ("colonize", "table")),
    PlanetCard("k_widow", "K-Widow", DieFace.ECONOMY, 6, 7, Resource.CULTURE, "regress_enemy_any_1", "Regress an enemy ship 1 space.", ("attack",)),
    PlanetCard("piedes", "Piedes", DieFace.ECONOMY, 6, 7, Resource.ENERGY, "repeat_activated_die", "Repeat the action on an already activated die.", ("dice_control", "wild")),
    PlanetCard("gyore", "Gyore", DieFace.ECONOMY, 6, 7, Resource.CULTURE, "set_inactive_die", "Set 1 inactive die to a face of your choice.", ("dice_control",)),
]
