from __future__ import annotations

from .model import DieFace, EmpirePersonality, PlanetCard, Resource, RivalDifficultyCard, RivalEmpireProfile, UpgradeCard


UPGRADES = [
    UpgradeCard(
        "warp_couriers",
        "Warp Couriers",
        DieFace.MOVE,
        "move_orbit_resource",
        "After you use a Move a Ship die, if the moved ship is on an orbit track, gain 1 energy or 1 culture.",
        ("mobility",),
    ),
    UpgradeCard(
        "frontier_beacons",
        "Frontier Beacons",
        DieFace.MOVE,
        "move_colony_progress",
        "After you use a Move a Ship die, choose an orbiting ship and advance it if it has progress, or if you have no colonies and spend 1 energy.",
        ("mobility", "colonize"),
    ),
    UpgradeCard(
        "orbital_refineries",
        "Orbital Refineries",
        DieFace.ENERGY,
        "extra_energy",
        "After you use an Acquire Energy die, gain 1 additional energy.",
        ("economy",),
    ),
    UpgradeCard(
        "fusion_tithes",
        "Fusion Tithes",
        DieFace.ENERGY,
        "energy_vp_with_colonies",
        "After you use an Acquire Energy die, gain 1 VP if you have at least two colonized planets.",
        ("economy", "score"),
    ),
    UpgradeCard(
        "cultural_archives",
        "Cultural Archives",
        DieFace.CULTURE,
        "extra_culture_with_colony",
        "After you use an Acquire Culture die, gain 1 additional culture if you have a colonized planet.",
        ("culture",),
    ),
    UpgradeCard(
        "soft_power_networks",
        "Soft Power Networks",
        DieFace.CULTURE,
        "culture_diplomacy_progress",
        "The first time each turn you use an Acquire Culture die, advance one ship on a diplomacy colony track 1 space.",
        ("culture", "diplomacy"),
    ),
    UpgradeCard(
        "trade_league",
        "Trade League",
        DieFace.ECONOMY,
        "economy_culture",
        "After you use an Advance Economy die, gain 1 culture.",
        ("economy", "culture"),
    ),
    UpgradeCard(
        "merchant_convoys",
        "Merchant Convoys",
        DieFace.ECONOMY,
        "economy_colony_energy",
        "After you use an Advance Economy die, gain energy equal to your colonized planets, max 2.",
        ("economy",),
    ),
    UpgradeCard(
        "envoy_corps",
        "Envoy Corps",
        DieFace.DIPLOMACY,
        "extra_diplomacy_progress",
        "After you use an Advance Diplomacy die, advance one ship on a diplomacy colony track 1 additional space.",
        ("diplomacy",),
    ),
    UpgradeCard(
        "charter_worlds",
        "Charter Worlds",
        DieFace.DIPLOMACY,
        "diplomacy_claim_vp",
        "When an Advance Diplomacy die causes you to colonize a planet, gain 1 VP.",
        ("diplomacy", "score"),
    ),
    UpgradeCard(
        "colony_prefabs",
        "Colony Prefabs",
        DieFace.COLONY,
        "extra_colony_progress",
        "After you use a Utilize Colony die, advance one ship on a colony track 1 space.",
        ("colonize",),
    ),
    UpgradeCard(
        "settler_mandate",
        "Settler Mandate",
        DieFace.COLONY,
        "colony_claim_culture",
        "When a Utilize Colony die causes you to colonize a planet, gain 1 culture and 1 VP.",
        ("colonize", "culture"),
    ),
]


PERSONALITIES = [
    EmpirePersonality(
        "frontier_union",
        "Frontier Union",
        "Solo priority: Move > Colony > Energy > Diplomacy. Prefers movement and colonization upgrades.",
        (DieFace.MOVE, DieFace.COLONY, DieFace.ENERGY, DieFace.DIPLOMACY),
        (DieFace.MOVE, DieFace.COLONY),
    ),
    EmpirePersonality(
        "star_cartel",
        "Star Cartel",
        "Solo priority: Economy > Energy > Culture > Colony. Prefers resource upgrades.",
        (DieFace.ECONOMY, DieFace.ENERGY, DieFace.CULTURE, DieFace.COLONY),
        (DieFace.ECONOMY, DieFace.ENERGY),
    ),
    EmpirePersonality(
        "archive_compact",
        "Archive Compact",
        "Solo priority: Culture > Diplomacy > Economy > Energy. Prefers culture and diplomacy upgrades.",
        (DieFace.CULTURE, DieFace.DIPLOMACY, DieFace.ECONOMY, DieFace.ENERGY),
        (DieFace.CULTURE, DieFace.DIPLOMACY),
    ),
    EmpirePersonality(
        "settlement_charter",
        "Settlement Charter",
        "Solo priority: Colony > Diplomacy > Move > Culture. Prefers planet-claiming upgrades.",
        (DieFace.COLONY, DieFace.DIPLOMACY, DieFace.MOVE, DieFace.CULTURE),
        (DieFace.COLONY, DieFace.DIPLOMACY),
    ),
]


RIVAL_EMPIRES = [
    RivalEmpireProfile(
        "devourer_swarm",
        "Devourer Swarm",
        "Rival Empire: races for short colony tracks and knocks back your strongest orbiting ship.",
        (DieFace.MOVE, DieFace.COLONY, DieFace.ECONOMY, DieFace.DIPLOMACY, DieFace.ENERGY, DieFace.CULTURE),
        "short_tracks",
        "regress_player_orbit",
        ("colonize", "score"),
    ),
    RivalEmpireProfile(
        "iron_directorate",
        "Iron Directorate",
        "Rival Empire: builds its empire early and taxes your resources when it colonizes.",
        (DieFace.COLONY, DieFace.ENERGY, DieFace.ECONOMY, DieFace.MOVE, DieFace.DIPLOMACY, DieFace.CULTURE),
        "empire_upgrade",
        "tax_resources",
        ("upgrade", "energy"),
    ),
    RivalEmpireProfile(
        "void_corsairs",
        "Void Corsairs",
        "Rival Empire: contests rich planets and steals your highest resource when it colonizes.",
        (DieFace.MOVE, DieFace.ENERGY, DieFace.CULTURE, DieFace.ECONOMY, DieFace.DIPLOMACY, DieFace.COLONY),
        "resource_denial",
        "steal_resource",
        ("energy", "culture"),
    ),
    RivalEmpireProfile(
        "oracle_singularity",
        "Oracle Singularity",
        "Rival Empire: prefers culture and diplomacy, and blocks Follow after it colonizes.",
        (DieFace.CULTURE, DieFace.DIPLOMACY, DieFace.COLONY, DieFace.MOVE, DieFace.ECONOMY, DieFace.ENERGY),
        "dice_control",
        "lock_follow",
        ("diplomacy", "culture"),
    ),
]


RIVAL_DIFFICULTIES = [
    RivalDifficultyCard(
        "training",
        "Training",
        "Easy difficulty: rival starts at empire level 1 with reduced resources and no VP.",
        empire_level=1,
        energy=1,
        culture=1,
        vp=0,
    ),
    RivalDifficultyCard(
        "standard",
        "Standard",
        "Normal difficulty: rival starts at empire level 1 with baseline resources and 2 VP.",
        empire_level=1,
        energy=2,
        culture=1,
        vp=2,
    ),
    RivalDifficultyCard(
        "advanced",
        "Advanced",
        "Hard difficulty: rival starts at empire level 1 with extra energy and 4 VP.",
        empire_level=1,
        energy=3,
        culture=1,
        vp=4,
    ),
    RivalDifficultyCard(
        "expert",
        "Expert",
        "Expert difficulty: rival starts at empire level 1 with extra energy and 6 VP.",
        empire_level=1,
        energy=3,
        culture=1,
        vp=6,
    ),
]


PROTOTYPE_PLANETS = [
    PlanetCard(
        "asterion_gate",
        "Asterion Gate",
        DieFace.ECONOMY,
        3,
        2,
        Resource.ENERGY,
        "energy_on_claim",
        "When colonized, gain 2 energy.",
        ("economy", "energy"),
    ),
    PlanetCard(
        "lyra_archive",
        "Lyra Archive",
        DieFace.DIPLOMACY,
        3,
        2,
        Resource.CULTURE,
        "culture_on_claim",
        "When colonized, gain 2 culture.",
        ("culture", "diplomacy"),
    ),
    PlanetCard(
        "vesta_foundry",
        "Vesta Foundry",
        DieFace.ECONOMY,
        4,
        3,
        Resource.ENERGY,
        "energy_faces_plus",
        "Your Acquire Energy dice gain 1 additional energy.",
        ("economy", "energy"),
    ),
    PlanetCard(
        "eidolon_forum",
        "Eidolon Forum",
        DieFace.DIPLOMACY,
        4,
        3,
        Resource.CULTURE,
        "culture_faces_plus",
        "Your Acquire Culture dice gain 1 additional culture.",
        ("culture", "diplomacy"),
    ),
    PlanetCard(
        "nova_yards",
        "Nova Yards",
        DieFace.ECONOMY,
        4,
        3,
        Resource.ENERGY,
        "move_energy",
        "After you use a Move a Ship die, gain 1 energy.",
        ("mobility", "energy"),
    ),
    PlanetCard(
        "parallax_sanctum",
        "Parallax Sanctum",
        DieFace.DIPLOMACY,
        4,
        3,
        Resource.CULTURE,
        "move_culture",
        "After you use a Move a Ship die, gain 1 culture.",
        ("mobility", "culture"),
    ),
    PlanetCard(
        "orion_expanse",
        "Orion Expanse",
        DieFace.ECONOMY,
        5,
        4,
        Resource.MIXED,
        "economy_vp",
        "The first time each turn you use an Advance Economy die, gain 1 VP.",
        ("economy", "score"),
    ),
    PlanetCard(
        "seraph_accord",
        "Seraph Accord",
        DieFace.DIPLOMACY,
        5,
        4,
        Resource.MIXED,
        "diplomacy_vp",
        "The first time each turn you use an Advance Diplomacy die, gain 1 VP.",
        ("diplomacy", "score"),
    ),
    PlanetCard(
        "helio_basin",
        "Helio Basin",
        DieFace.ECONOMY,
        3,
        2,
        Resource.ENERGY,
        "upgrade_energy_discount",
        "Your first upgrade bought with energy costs 1 less.",
        ("economy", "upgrade"),
    ),
    PlanetCard(
        "meridian_cloister",
        "Meridian Cloister",
        DieFace.DIPLOMACY,
        3,
        2,
        Resource.CULTURE,
        "upgrade_culture_discount",
        "Your first upgrade bought with culture costs 1 less.",
        ("culture", "upgrade"),
    ),
    PlanetCard(
        "kepler_bazaar",
        "Kepler Bazaar",
        DieFace.ECONOMY,
        4,
        2,
        Resource.MIXED,
        "economy_culture",
        "After you use an Advance Economy die, gain 1 culture.",
        ("economy", "culture"),
    ),
    PlanetCard(
        "cyris_embassy",
        "Cyris Embassy",
        DieFace.DIPLOMACY,
        4,
        2,
        Resource.MIXED,
        "diplomacy_energy",
        "After you use an Advance Diplomacy die, gain 1 energy.",
        ("diplomacy", "energy"),
    ),
    PlanetCard(
        "titan_ring",
        "Titan Ring",
        DieFace.ECONOMY,
        5,
        5,
        Resource.ENERGY,
        "none",
        "High-value energy world.",
        ("economy", "score"),
    ),
    PlanetCard(
        "arcadia_prime",
        "Arcadia Prime",
        DieFace.DIPLOMACY,
        5,
        5,
        Resource.CULTURE,
        "none",
        "High-value culture world.",
        ("diplomacy", "score"),
    ),
    PlanetCard(
        "sagan_relay",
        "Sagan Relay",
        DieFace.ECONOMY,
        3,
        1,
        Resource.ENERGY,
        "move_progress",
        "After you use a Move a Ship die, advance one of your ships on a colony track 1 space.",
        ("mobility", "colonize"),
    ),
    PlanetCard(
        "mnemosyne_hall",
        "Mnemosyne Hall",
        DieFace.DIPLOMACY,
        3,
        1,
        Resource.CULTURE,
        "culture_progress",
        "After you use an Acquire Culture die, advance one of your ships on a diplomacy colony track 1 space.",
        ("culture", "diplomacy"),
    ),
    PlanetCard(
        "iridium_moon",
        "Iridium Moon",
        DieFace.ECONOMY,
        2,
        1,
        Resource.ENERGY,
        "energy_on_claim",
        "When colonized, gain 2 energy.",
        ("economy",),
    ),
    PlanetCard(
        "chorus_moon",
        "Chorus Moon",
        DieFace.DIPLOMACY,
        2,
        1,
        Resource.CULTURE,
        "culture_on_claim",
        "When colonized, gain 2 culture.",
        ("culture",),
    ),
    PlanetCard(
        "daedalus_array",
        "Daedalus Array",
        DieFace.ECONOMY,
        4,
        3,
        Resource.ENERGY,
        "upgrade_vp",
        "When you buy an upgrade, gain 1 VP.",
        ("upgrade", "score"),
    ),
    PlanetCard(
        "vesper_court",
        "Vesper Court",
        DieFace.DIPLOMACY,
        4,
        3,
        Resource.CULTURE,
        "claim_culture_vp",
        "When you colonize a culture planet, gain 1 VP.",
        ("culture", "score"),
    ),
    PlanetCard(
        "prometheus_labs",
        "Prometheus Labs",
        DieFace.ECONOMY,
        4,
        3,
        Resource.MIXED,
        "upgrade_draw",
        "When you buy an upgrade, cycle the oldest market upgrade.",
        ("upgrade",),
    ),
    PlanetCard(
        "harmony_spire",
        "Harmony Spire",
        DieFace.DIPLOMACY,
        4,
        3,
        Resource.MIXED,
        "balanced_income",
        "After you use Culture and Energy dice in the same turn, gain 1 VP.",
        ("culture", "energy", "score"),
    ),
    PlanetCard(
        "umbra_outpost",
        "Umbra Outpost",
        DieFace.ECONOMY,
        3,
        2,
        Resource.ENERGY,
        "ship_on_claim",
        "When colonized, return one additional ship from a planet to your Galaxy mat if able.",
        ("mobility",),
    ),
    PlanetCard(
        "solace_haven",
        "Solace Haven",
        DieFace.DIPLOMACY,
        3,
        2,
        Resource.CULTURE,
        "vp_on_claim",
        "When colonized, gain 1 VP.",
        ("diplomacy", "score"),
    ),
    PlanetCard(
        "zenith_colony",
        "Zenith Colony",
        DieFace.ECONOMY,
        5,
        4,
        Resource.ENERGY,
        "colony_energy",
        "After you use a Utilize Colony die, gain 1 energy.",
        ("colonize", "energy"),
    ),
    PlanetCard(
        "halcyon_colony",
        "Halcyon Colony",
        DieFace.DIPLOMACY,
        5,
        4,
        Resource.CULTURE,
        "colony_culture",
        "After you use a Utilize Colony die, gain 1 culture.",
        ("colonize", "culture"),
    ),
    PlanetCard(
        "lambda_refuge",
        "Lambda Refuge",
        DieFace.ECONOMY,
        3,
        2,
        Resource.MIXED,
        "low_resource_vp",
        "If you end your turn with 2 or fewer total resources, gain 1 VP.",
        ("score",),
    ),
    PlanetCard(
        "aurelia_crown",
        "Aurelia Crown",
        DieFace.DIPLOMACY,
        5,
        5,
        Resource.MIXED,
        "three_upgrade_vp",
        "At game end, gain 2 VP if you have three upgrades.",
        ("upgrade", "score"),
    ),
    PlanetCard(
        "draco_station",
        "Draco Station",
        DieFace.ECONOMY,
        4,
        3,
        Resource.ENERGY,
        "energy_colony_progress",
        "After you use an Acquire Energy die, advance one of your ships on an economy colony track 1 space.",
        ("economy", "energy"),
    ),
    PlanetCard(
        "lotus_station",
        "Lotus Station",
        DieFace.DIPLOMACY,
        4,
        3,
        Resource.CULTURE,
        "diplomacy_culture",
        "After you use an Advance Diplomacy die, gain 1 culture.",
        ("diplomacy", "culture"),
    ),
    PlanetCard(
        "eos_mirror",
        "Eos Mirror",
        DieFace.ECONOMY,
        3,
        2,
        Resource.MIXED,
        "resource_balance",
        "After you use an Acquire Energy die, gain 1 culture if you have less culture than energy.",
        ("energy", "culture"),
    ),
    PlanetCard(
        "nocturne_mirror",
        "Nocturne Mirror",
        DieFace.DIPLOMACY,
        3,
        2,
        Resource.MIXED,
        "culture_balance",
        "After you use an Acquire Culture die, gain 1 energy if you have less energy than culture.",
        ("culture", "energy"),
    ),
    PlanetCard(
        "bastion_minor",
        "Bastion Minor",
        DieFace.ECONOMY,
        2,
        1,
        Resource.ENERGY,
        "economy_on_claim_vp",
        "When colonized by Economy, gain 1 VP.",
        ("economy", "score"),
    ),
    PlanetCard(
        "concord_minor",
        "Concord Minor",
        DieFace.DIPLOMACY,
        2,
        1,
        Resource.CULTURE,
        "diplomacy_on_claim_vp",
        "When colonized by Diplomacy, gain 1 VP.",
        ("diplomacy", "score"),
    ),
    PlanetCard(
        "apex_world",
        "Apex World",
        DieFace.ECONOMY,
        6,
        6,
        Resource.ENERGY,
        "end_energy_vp",
        "At game end, gain 1 VP for every 4 energy.",
        ("economy", "score"),
    ),
    PlanetCard(
        "elysium_world",
        "Elysium World",
        DieFace.DIPLOMACY,
        6,
        6,
        Resource.CULTURE,
        "end_culture_vp",
        "At game end, gain 1 VP for every 4 culture.",
        ("culture", "score"),
    ),
]


from .base_planets import BASE_PLANETS


PLANETS = BASE_PLANETS
