from __future__ import annotations

from .model import DieColor, Tile, TileKind


# Generated from Roll_for_the_Galaxy_all_tiles.xls.
# Only structured fields are retained; full tile text is not copied.
NON_START_TILES: tuple[Tile, ...] = (
    Tile('advanced_logistics', 'Advanced Logistics', TileKind.DEVELOPMENT, 1, 1, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_i',)),
    Tile('alien_research_ship', 'Alien Research Ship', TileKind.DEVELOPMENT, 5, 5, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_i',)),
    Tile('alien_research_team', 'Alien Research Team', TileKind.DEVELOPMENT, 3, 3, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_i',)),
    Tile('alien_robot_scout_ship', 'Alien Robot Scout Ship', TileKind.WORLD, 4, 4, grants=(DieColor.YELLOW,), placement='cup', die_loss=0, immediate_credits=1, world_color='Alien Technology', produces=True, tags=('alien_technology',)),
    Tile('alien_sentinels', 'Alien Sentinels', TileKind.WORLD, 6, 6, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='Alien Technology', produces=True, tags=('alien_technology',)),
    Tile('alien_uplift_blueprints', 'Alien Uplift Blueprints', TileKind.DEVELOPMENT, 3, 3, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_iii',)),
    Tile('armaments_world', 'Armaments World', TileKind.WORLD, 4, 4, grants=(DieColor.BROWN,), placement='world', die_loss=0, immediate_credits=1, world_color='Rare Elemental', produces=True, tags=('rare_elemental',)),
    Tile('artist_colony', 'Artist Colony', TileKind.WORLD, 1, 1, grants=(DieColor.BLUE,), placement='citizenry', die_loss=0, immediate_credits=0, world_color='Novelty', produces=True, tags=('novelty',)),
    Tile('asteroid_belt', 'Asteroid Belt', TileKind.WORLD, 2, 2, grants=(DieColor.BROWN,), placement='cup', die_loss=0, immediate_credits=0, world_color='Rare Elemental', produces=True, tags=('rare_elemental',)),
    Tile('backup_planning', 'Backup Planning', TileKind.DEVELOPMENT, 1, 1, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('reassign',)),
    Tile('blaster_gem_mines', 'Blaster Gem mines', TileKind.WORLD, 3, 3, grants=(DieColor.RED, DieColor.BROWN), placement='citizenry', die_loss=0, immediate_credits=0, world_color='Rare Elemental', produces=True, tags=('rare_elemental',)),
    Tile('colonial_affinity', 'Colonial Affinity', TileKind.DEVELOPMENT, 2, 2, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('reassign',)),
    Tile('comet_zone', 'Comet Zone', TileKind.WORLD, 3, 3, grants=(DieColor.BROWN,), placement='world', die_loss=0, immediate_credits=0, world_color='Rare Elemental', produces=True, tags=('rare_elemental',)),
    Tile('conscription', 'Conscription', TileKind.DEVELOPMENT, 4, 4, grants=(DieColor.RED, DieColor.RED), placement='cup', die_loss=1, immediate_credits=0, world_color='', produces=False, tags=()),
    Tile('deep_space_symbionts_ltd', 'Deep Space Symbionts, Ltd', TileKind.WORLD, 4, 4, grants=(DieColor.GREEN,), placement='cup', die_loss=0, immediate_credits=1, world_color='Genes', produces=True, tags=('genes',)),
    Tile('deserted_alien_colony', 'Deserted Alien Colony', TileKind.WORLD, 5, 5, grants=(DieColor.YELLOW,), placement='world', die_loss=0, immediate_credits=1, world_color='Alien Technology', produces=True, tags=('alien_technology',)),
    Tile('deserted_alien_library', 'Deserted Alien Library', TileKind.WORLD, 6, 6, grants=(DieColor.YELLOW,), placement='world', die_loss=0, immediate_credits=2, world_color='Alien Technology', produces=True, tags=('alien_technology',)),
    Tile('deserted_alien_outpost', 'Deserted Alien Outpost', TileKind.WORLD, 4, 4, grants=(DieColor.YELLOW,), placement='world', die_loss=0, immediate_credits=0, world_color='Alien Technology', produces=True, tags=('alien_technology',)),
    Tile('designer_species_ultd', 'Designer Species, ULTD.', TileKind.WORLD, 5, 5, grants=(DieColor.GREEN,), placement='world', die_loss=0, immediate_credits=1, world_color='Genes', produces=True, tags=('genes',)),
    Tile('distant_world', 'Distant World', TileKind.WORLD, 4, 4, grants=(DieColor.GREEN,), placement='cup', die_loss=0, immediate_credits=0, world_color='Genes', produces=True, tags=('genes',)),
    Tile('diversification', 'Diversification', TileKind.DEVELOPMENT, 1, 1, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('reassign',)),
    Tile('executive_power', 'Executive Power', TileKind.DEVELOPMENT, 3, 3, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('reassign',)),
    Tile('export_duties', 'Export Duties', TileKind.DEVELOPMENT, 2, 2, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_v',)),
    Tile('fifth_column', 'Fifth Column', TileKind.WORLD, 1, 1, grants=(DieColor.RED,), placement='cup', die_loss=0, immediate_credits=0, world_color='gray', produces=False, tags=('gray',)),
    Tile('former_penal_colony', 'Former Penal Colony', TileKind.WORLD, 1, 1, grants=(DieColor.RED,), placement='cup', die_loss=1, immediate_credits=0, world_color='Novelty', produces=True, tags=('novelty',)),
    Tile('free_trade_association', 'Free Trade Association', TileKind.DEVELOPMENT, 6, 6, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_v', 'end_game')),
    Tile('free_trade_zone', 'Free Trade Zone', TileKind.DEVELOPMENT, 3, 3, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_iii',)),
    Tile('galactic_bankers', 'Galactic Bankers', TileKind.DEVELOPMENT, 6, 6, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_v', 'end_game')),
    Tile('galactic_demand', 'Galactic Demand', TileKind.DEVELOPMENT, 2, 2, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_v',)),
    Tile('galactic_exchange', 'Galactic Exchange', TileKind.DEVELOPMENT, 6, 6, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_iii', 'end_game')),
    Tile('galactic_federation', 'Galactic Federation', TileKind.DEVELOPMENT, 6, 6, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_ii', 'end_game')),
    Tile('galactic_fuel_depot', 'Galactic Fuel Depot', TileKind.WORLD, 3, 3, grants=(DieColor.BROWN,), placement='world', die_loss=0, immediate_credits=0, world_color='Rare Elemental', produces=True, tags=('rare_elemental',)),
    Tile('galactic_influence', 'Galactic Influence', TileKind.DEVELOPMENT, 3, 3, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('reassign',)),
    Tile('galactic_investors', 'Galactic Investors', TileKind.DEVELOPMENT, 5, 5, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_ii',)),
    Tile('galactic_mandate', 'Galactic Mandate', TileKind.DEVELOPMENT, 3, 3, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('reassign',)),
    Tile('galactic_recycling', 'Galactic Recycling', TileKind.DEVELOPMENT, 2, 2, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_ii', 'phase_iii')),
    Tile('galactic_renaissance', 'Galactic Renaissance', TileKind.DEVELOPMENT, 6, 6, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_v', 'end_game')),
    Tile('galactic_reserves', 'Galactic Reserves', TileKind.DEVELOPMENT, 6, 6, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_v', 'end_game')),
    Tile('galactic_resort', 'Galactic Resort', TileKind.WORLD, 3, 3, grants=(DieColor.BLUE,), placement='world', die_loss=0, immediate_credits=0, world_color='Novelty', produces=True, tags=('novelty',)),
    Tile('galactic_salon', 'Galactic Salon', TileKind.DEVELOPMENT, 4, 4, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_v',)),
    Tile('galactic_survey_headquarters', 'Galactic Survey Headquarters', TileKind.WORLD, 2, 2, grants=(DieColor.BLUE,), placement='cup', die_loss=0, immediate_credits=0, world_color='Novelty', produces=True, tags=('novelty',)),
    Tile('galactic_trendsetters', 'Galactic Trendsetters', TileKind.WORLD, 6, 6, grants=(DieColor.PURPLE, DieColor.PURPLE), placement='citizenry', die_loss=0, immediate_credits=1, world_color='gray', produces=False, tags=('gray',)),
    Tile('gateway_station', 'Gateway Station', TileKind.WORLD, 3, 3, grants=(DieColor.PURPLE,), placement='citizenry', die_loss=0, immediate_credits=0, world_color='gray', produces=False, tags=('gray',)),
    Tile('gem_world', 'Gem World', TileKind.WORLD, 2, 2, grants=(DieColor.BLUE,), placement='cup', die_loss=0, immediate_credits=0, world_color='Novelty', produces=True, tags=('novelty',)),
    Tile('high_gravity_world', 'High Gravity World', TileKind.WORLD, 1, 1, grants=(DieColor.RED,), placement='cup', die_loss=0, immediate_credits=0, world_color='gray', produces=False, tags=('gray',)),
    Tile('homeworld_patriotism', 'Homeworld Patriotism', TileKind.DEVELOPMENT, 3, 3, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('reassign',)),
    Tile('hydroponics_guild', 'Hydroponics Guild', TileKind.DEVELOPMENT, 1, 1, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('reassign',)),
    Tile('information_hub', 'Information Hub', TileKind.WORLD, 3, 3, grants=(DieColor.BLUE,), placement='world', die_loss=0, immediate_credits=0, world_color='Novelty', produces=True, tags=('novelty',)),
    Tile('information_tech', 'Information Tech', TileKind.DEVELOPMENT, 4, 4, grants=(DieColor.BLUE, DieColor.BLUE), placement='cup', die_loss=1, immediate_credits=0, world_color='', produces=False, tags=()),
    Tile('investment_credits', 'Investment Credits', TileKind.DEVELOPMENT, 4, 4, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_ii',)),
    Tile('isolation_policy', 'Isolation Policy', TileKind.DEVELOPMENT, 3, 3, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('reassign',)),
    Tile('jumpdrive_fuel_refinery', 'Jumpdrive Fuel Refinery', TileKind.WORLD, 3, 3, grants=(DieColor.BROWN,), placement='world', die_loss=0, immediate_credits=0, world_color='Rare Elemental', produces=True, tags=('rare_elemental',)),
    Tile('jumpdrive_research', 'Jumpdrive Research', TileKind.DEVELOPMENT, 1, 1, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='gray', produces=False, tags=('phase_v', 'gray')),
    Tile('jungle_world', 'Jungle World', TileKind.WORLD, 4, 4, grants=(DieColor.GREEN,), placement='world', die_loss=0, immediate_credits=0, world_color='Genes', produces=True, tags=('genes',)),
    Tile('local_subsidies', 'Local Subsidies', TileKind.DEVELOPMENT, 2, 2, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('reassign',)),
    Tile('lost_alien_battle_fleet', 'Lost Alien Battle Fleet', TileKind.WORLD, 6, 6, grants=(DieColor.YELLOW,), placement='cup', die_loss=0, immediate_credits=3, world_color='Alien Technology', produces=True, tags=('alien_technology',)),
    Tile('lost_alien_warship', 'Lost Alien Warship', TileKind.WORLD, 5, 5, grants=(DieColor.YELLOW,), placement='cup', die_loss=0, immediate_credits=2, world_color='Alien Technology', produces=True, tags=('alien_technology',)),
    Tile('lost_species_ark_world', 'Lost Species Ark World', TileKind.WORLD, 5, 5, grants=(DieColor.GREEN,), placement='world', die_loss=0, immediate_credits=1, world_color='Genes', produces=True, tags=('genes',)),
    Tile('mad_scientists', 'Mad Scientists', TileKind.DEVELOPMENT, 3, 3, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('reassign',)),
    Tile('major_research_labs', 'Major Research Labs', TileKind.DEVELOPMENT, 3, 3, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_i',)),
    Tile('malevolent_lifeforms', 'Malevolent Lifeforms', TileKind.WORLD, 4, 4, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='Genes', produces=True, tags=('genes',)),
    Tile('merchant_guild', 'Merchant Guild', TileKind.DEVELOPMENT, 3, 3, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_v',)),
    Tile('mining_league', 'Mining League', TileKind.DEVELOPMENT, 6, 6, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_v', 'end_game')),
    Tile('mining_world', 'Mining World', TileKind.WORLD, 3, 3, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='Rare Elemental', produces=True, tags=('rare_elemental',)),
    Tile('minor_research_labs', 'Minor Research Labs', TileKind.DEVELOPMENT, 2, 2, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_v',)),
    Tile('nanotechnology', 'Nanotechnology', TileKind.DEVELOPMENT, 5, 5, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('reassign',)),
    Tile('new_economy', 'New Economy', TileKind.DEVELOPMENT, 6, 6, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_v', 'end_game')),
    Tile('new_galactic_order', 'New Galactic Order', TileKind.DEVELOPMENT, 6, 6, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_iii', 'end_game')),
    Tile('new_survivalists', 'New Survivalists', TileKind.WORLD, 1, 1, grants=(DieColor.BLUE,), placement='citizenry', die_loss=0, immediate_credits=0, world_color='Novelty', produces=True, tags=('novelty',)),
    Tile('new_vinland', 'New Vinland', TileKind.WORLD, 2, 2, grants=(DieColor.BLUE,), placement='cup', die_loss=0, immediate_credits=0, world_color='Novelty', produces=True, tags=('novelty',)),
    Tile('operations_affinity', 'Operations Affinity', TileKind.DEVELOPMENT, 2, 2, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('reassign',)),
    Tile('ore_rich_world', 'Ore-Rich World', TileKind.WORLD, 2, 2, grants=(DieColor.BROWN,), placement='cup', die_loss=0, immediate_credits=0, world_color='Rare Elemental', produces=True, tags=('rare_elemental',)),
    Tile('organic_shipyards', 'Organic Shipyards', TileKind.DEVELOPMENT, 5, 5, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_v',)),
    Tile('outlaw_world', 'Outlaw World', TileKind.WORLD, 2, 2, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='gray', produces=False, tags=('gray',)),
    Tile('pirate_world', 'Pirate World', TileKind.WORLD, 2, 2, grants=(DieColor.RED,), placement='citizenry', die_loss=0, immediate_credits=0, world_color='Novelty', produces=True, tags=('novelty',)),
    Tile('plague_world', 'Plague World', TileKind.WORLD, 3, 3, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='Genes', produces=True, tags=('genes',)),
    Tile('planetary_nebula', 'Planetary Nebula', TileKind.WORLD, 3, 3, grants=(DieColor.BROWN,), placement='world', die_loss=0, immediate_credits=0, world_color='Rare Elemental', produces=True, tags=('rare_elemental',)),
    Tile('propaganda_campaign', 'Propaganda Campaign', TileKind.DEVELOPMENT, 4, 4, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('reassign',)),
    Tile('prosperous_world', 'Prosperous World', TileKind.WORLD, 3, 3, grants=(DieColor.BLUE,), placement='world', die_loss=0, immediate_credits=0, world_color='Novelty', produces=True, tags=('novelty',)),
    Tile('public_works', 'Public Works', TileKind.DEVELOPMENT, 1, 1, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_ii',)),
    Tile('radioactive_world', 'Radioactive World', TileKind.WORLD, 2, 2, grants=(DieColor.BROWN,), placement='cup', die_loss=0, immediate_credits=0, world_color='Rare Elemental', produces=True, tags=('rare_elemental',)),
    Tile('rebel_hideout', 'Rebel Hideout', TileKind.WORLD, 2, 2, grants=(DieColor.RED, DieColor.RED), placement='citizenry', die_loss=0, immediate_credits=0, world_color='gray', produces=False, tags=('gray',)),
    Tile('rebel_miners', 'Rebel Miners', TileKind.WORLD, 2, 2, grants=(DieColor.RED, DieColor.RED), placement='citizenry', die_loss=1, immediate_credits=0, world_color='Rare Elemental', produces=True, tags=('rare_elemental',)),
    Tile('rebel_warrior_race', 'Rebel Warrior Race', TileKind.WORLD, 3, 3, grants=(DieColor.RED, DieColor.GREEN), placement='citizenry', die_loss=1, immediate_credits=0, world_color='Genes', produces=True, tags=('genes',)),
    Tile('replicant_robots', 'Replicant Robots', TileKind.DEVELOPMENT, 4, 4, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_iii',)),
    Tile('robot_surveyors', 'Robot Surveyors', TileKind.DEVELOPMENT, 5, 5, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_iii',)),
    Tile('runaway_robots', 'Runaway Robots', TileKind.WORLD, 2, 2, grants=(DieColor.RED,), placement='cup', die_loss=0, immediate_credits=0, world_color='Rare Elemental', produces=True, tags=('rare_elemental',)),
    Tile('secluded_world', 'Secluded World', TileKind.WORLD, 1, 1, grants=(DieColor.BLUE,), placement='citizenry', die_loss=0, immediate_credits=0, world_color='Novelty', produces=True, tags=('novelty',)),
    Tile('sentient_robots', 'Sentient Robots', TileKind.WORLD, 2, 2, grants=(DieColor.RED,), placement='cup', die_loss=0, immediate_credits=0, world_color='gray', produces=False, tags=('gray',)),
    Tile('shipping_affinity', 'Shipping Affinity', TileKind.DEVELOPMENT, 2, 2, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('reassign',)),
    Tile('silicon_world', 'Silicon World', TileKind.WORLD, 4, 4, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='Rare Elemental', produces=True, tags=('rare_elemental',)),
    Tile('space_docks', 'Space Docks', TileKind.DEVELOPMENT, 2, 2, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_v',)),
    Tile('space_marines', 'Space Marines', TileKind.DEVELOPMENT, 3, 3, grants=(DieColor.RED,), placement='cup', die_loss=1, immediate_credits=1, world_color='', produces=False, tags=()),
    Tile('space_mercenaries', 'Space Mercenaries', TileKind.DEVELOPMENT, 1, 1, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('reassign',)),
    Tile('space_port', 'Space Port', TileKind.WORLD, 2, 2, grants=(DieColor.BLUE,), placement='cup', die_loss=0, immediate_credits=0, world_color='Novelty', produces=True, tags=('novelty',)),
    Tile('space_refineries', 'Space Refineries', TileKind.DEVELOPMENT, 3, 3, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_v',)),
    Tile('space_tourism', 'Space Tourism', TileKind.DEVELOPMENT, 3, 3, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='gray', produces=False, tags=('phase_v', 'gray')),
    Tile('spice_world', 'Spice World', TileKind.WORLD, 2, 2, grants=(DieColor.BLUE,), placement='cup', die_loss=0, immediate_credits=0, world_color='Novelty', produces=True, tags=('novelty',)),
    Tile('star_nomad_lair', 'Star Nomad Lair', TileKind.WORLD, 1, 1, grants=(DieColor.BLUE,), placement='citizenry', die_loss=0, immediate_credits=0, world_color='Novelty', produces=True, tags=('novelty',)),
    Tile('system_diversification', 'System Diversification', TileKind.DEVELOPMENT, 6, 6, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('end_game', 'reassign')),
    Tile('technology_affinity', 'Technology Affinity', TileKind.DEVELOPMENT, 2, 2, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('reassign',)),
    Tile('technology_unions', 'Technology Unions', TileKind.DEVELOPMENT, 1, 1, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_i', 'phase_v')),
    Tile('terraforming_robots', 'Terraforming Robots', TileKind.DEVELOPMENT, 1, 1, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_iii',)),
    Tile('terraforming_world', 'Terraforming World', TileKind.WORLD, 5, 5, grants=(DieColor.PURPLE,), placement='citizenry', die_loss=0, immediate_credits=2, world_color='gray', produces=False, tags=('gray',)),
    Tile('tourist_world', 'Tourist World', TileKind.WORLD, 4, 4, grants=(DieColor.PURPLE,), placement='citizenry', die_loss=0, immediate_credits=1, world_color='gray', produces=False, tags=('gray',)),
    Tile('trade_levies', 'Trade Levies', TileKind.DEVELOPMENT, 3, 3, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_iv',)),
    Tile('trading_world', 'Trading World', TileKind.WORLD, 3, 3, grants=(DieColor.PURPLE,), placement='citizenry', die_loss=0, immediate_credits=0, world_color='gray', produces=False, tags=('gray',)),
    Tile('transport_hub', 'Transport Hub', TileKind.WORLD, 4, 4, grants=(DieColor.PURPLE,), placement='citizenry', die_loss=0, immediate_credits=1, world_color='gray', produces=False, tags=('gray',)),
    Tile('universal_exports', 'Universal Exports', TileKind.WORLD, 3, 3, grants=(DieColor.BLUE,), placement='world', die_loss=0, immediate_credits=0, world_color='Novelty', produces=True, tags=('novelty',)),
    Tile('uplift_overseers', 'Uplift Overseers', TileKind.WORLD, 3, 3, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='Genes', produces=True, tags=('genes',)),
)


START_FACTION_PAIRS: tuple[tuple[Tile, Tile], ...] = (
    (
        Tile('space_piracy', 'Space Piracy', TileKind.DEVELOPMENT, 0, 0, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_v', 'faction')),
        Tile('hidden_fortress', 'Hidden Fortress', TileKind.WORLD, 2, 2, grants=(DieColor.RED,), placement='citizenry', die_loss=0, immediate_credits=0, world_color='gray', produces=False, tags=('gray', 'faction')),
    ),
    (
        Tile('alien_archeology', 'Alien Archeology', TileKind.DEVELOPMENT, 1, 1, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_i', 'faction')),
        Tile('alien_rosetta_stone_world', 'Alien Rosetta Stone World', TileKind.WORLD, 1, 1, grants=(DieColor.YELLOW,), placement='citizenry', die_loss=0, immediate_credits=0, world_color='gray', produces=False, tags=('gray', 'faction')),
    ),
    (
        Tile('consumer_markets', 'Consumer markets', TileKind.DEVELOPMENT, 3, 3, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_iv', 'faction')),
        Tile('space_mall', 'Space Mall', TileKind.WORLD, 0, 0, grants=(DieColor.BLUE,), placement='cup', die_loss=0, immediate_credits=0, world_color='Novelty', produces=True, tags=('novelty', 'faction')),
    ),
    (
        Tile('improved_reconnaissance', 'Improved Reconnaissance', TileKind.DEVELOPMENT, 2, 2, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_i', 'faction')),
        Tile('wormhole_station', 'Wormhole Station', TileKind.WORLD, 3, 3, grants=(DieColor.BROWN,), placement='cup', die_loss=0, immediate_credits=0, world_color='Rare Elemental', produces=True, tags=('rare_elemental', 'faction')),
    ),
    (
        Tile('genetics_lab', 'Genetics Lab', TileKind.DEVELOPMENT, 2, 2, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_iv', 'faction')),
        Tile('the_last_of_the_gnarssh', 'The Last Of The Gnarssh', TileKind.WORLD, 0, 0, grants=(DieColor.GREEN,), placement='citizenry', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('faction',)),
    ),
    (
        Tile('galactic_religion', 'Galactic Religion', TileKind.DEVELOPMENT, 2, 2, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_ii', 'faction')),
        Tile('pilgramage_world', 'Pilgramage World', TileKind.WORLD, 3, 3, grants=(DieColor.BLUE,), placement='citizenry', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('faction',)),
    ),
    (
        Tile('bilogical_adaptation', 'Bilogical Adaptation', TileKind.DEVELOPMENT, 2, 2, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_ii', 'faction')),
        Tile('aquatic_uplift_world', 'Aquatic Uplift World', TileKind.WORLD, 2, 2, grants=(DieColor.GREEN,), placement='cup', die_loss=0, immediate_credits=0, world_color='gray', produces=False, tags=('gray', 'faction')),
    ),
    (
        Tile('mining_industry', 'Mining Industry', TileKind.DEVELOPMENT, 2, 2, grants=(), placement='', die_loss=0, immediate_credits=0, world_color='', produces=False, tags=('phase_v', 'faction')),
        Tile('meteorite_planet', 'Meteorite Planet', TileKind.WORLD, 1, 1, grants=(DieColor.BROWN,), placement='citizenry', die_loss=0, immediate_credits=0, world_color='Rare Elemental', produces=True, tags=('rare_elemental', 'faction')),
    ),
    (
        Tile('destroyed_colony', 'Destroyed Colony', TileKind.WORLD, 0, 0, grants=(DieColor.RED,), placement='citizenry', die_loss=0, immediate_credits=0, world_color='gray', produces=False, tags=('gray', 'faction')),
        Tile('awakened_alien_outpost', 'Awakened Alien Outpost', TileKind.WORLD, 3, 3, grants=(DieColor.PURPLE,), placement='cup', die_loss=0, immediate_credits=0, world_color='Alien Technology', produces=True, tags=('alien_technology', 'faction')),
    ),
)


HOME_WORLDS: tuple[Tile, ...] = (
    Tile('old_earth', 'Old Earth', TileKind.WORLD, 3, 3, grants=(DieColor.PURPLE,), placement='citizenry', die_loss=0, immediate_credits=0, world_color='gray', produces=False, tags=('gray', 'home')),
    Tile('epsilon_eridani', 'Epsilon Eridani', TileKind.WORLD, 2, 2, grants=(DieColor.BLUE, DieColor.RED), placement='citizenry', die_loss=0, immediate_credits=0, world_color='gray', produces=False, tags=('gray', 'home')),
    Tile('alpha_centauri', 'Alpha Centauri', TileKind.WORLD, 1, 1, grants=(DieColor.BROWN,), placement='world', die_loss=0, immediate_credits=0, world_color='Rare Elemental', produces=True, tags=('rare_elemental', 'home')),
    Tile('new_sparta', 'New Sparta', TileKind.WORLD, 2, 2, grants=(DieColor.RED, DieColor.RED), placement='citizenry', die_loss=0, immediate_credits=0, world_color='gray', produces=False, tags=('gray', 'home')),
    Tile('earth_s_lost_colony', "Earth's Lost Colony", TileKind.WORLD, 2, 2, grants=(DieColor.BLUE,), placement='world', die_loss=0, immediate_credits=0, world_color='Novelty', produces=True, tags=('novelty', 'home')),
    Tile('separatist_colony', 'Separatist Colony', TileKind.WORLD, 2, 2, grants=(DieColor.RED,), placement='cup', die_loss=0, immediate_credits=0, world_color='gray', produces=False, tags=('gray', 'home')),
    Tile('ancient_race', 'Ancient Race', TileKind.WORLD, 0, 0, grants=(DieColor.GREEN,), placement='world', die_loss=0, immediate_credits=0, world_color='Genes', produces=True, tags=('genes', 'home')),
    Tile('damaged_alien_factory', 'Damaged Alien Factory', TileKind.WORLD, 1, 1, grants=(DieColor.YELLOW,), placement='citizenry', die_loss=0, immediate_credits=0, world_color='Alien Technology', produces=True, tags=('alien_technology', 'home')),
    Tile('doomed_world', 'Doomed World', TileKind.WORLD, 0, 0, grants=(), placement='', die_loss=0, immediate_credits=8, world_color='gray', produces=False, tags=('gray', 'home')),
)


SAMPLE_TILES = NON_START_TILES
